
// channel_invite automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type ChannelInvite struct {
    MaxAge int `json:"max_age"`
    MaxUses int `json:"max_uses"`
    Temporary bool `json:"temporary"`
    Unique bool `json:"unique"`
    TargetType int `json:"target_type"`
    TargetUserId string `json:"target_user_id"`
    TargetApplicationId string `json:"target_application_id"`
}

