
// channel_update automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type ChannelUpdate struct {
    Name string `json:"name"`
    Icon string `json:"icon"`
}

