
// channel automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk
type Channel struct {
    Id string `json:"id"`
    Type int `json:"type"`
    GuildId string `json:"guild_id"`
    Position int `json:"position"`
    Name string `json:"name"`
    Topic string `json:"topic"`
    Nsfw bool `json:"nsfw"`
    LastMessageId string `json:"last_message_id"`
    Bitrate int `json:"bitrate"`
    UserLimit int `json:"user_limit"`
    RateLimitPerUser int `json:"rate_limit_per_user"`
    Icon string `json:"icon"`
    OwnerId string `json:"owner_id"`
    ApplicationId string `json:"application_id"`
    Managed bool `json:"managed"`
    ParentId string `json:"parent_id"`
    LastPinTimestamp string `json:"last_pin_timestamp"`
    RtcRegion string `json:"rtc_region"`
    VideoQualityMode int `json:"video_quality_mode"`
    MessageCount int `json:"message_count"`
    MemberCount int `json:"member_count"`
    DefaultAutoArchiveDuration int `json:"default_auto_archive_duration"`
    Permissions string `json:"permissions"`
    Flags int `json:"flags"`
    TotalMessageSent int `json:"total_message_sent"`
    DefaultSortOrder int `json:"default_sort_order"`
    DefaultForumLayout int `json:"default_forum_layout"`
}
