
// error automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type Error struct {
    Code int `json:"code"`
    Message string `json:"message"`
    Errors any `json:`
}

