
// MessageTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

import (
    "bytes"
    "encoding/json"
    "errors"
    "fmt"
    
    "io"
    "net/http"
    "net/url"
    
)

type MessageTag struct {
    internal *sdkgen.TagAbstract
}



// GetAll Retrieves the messages in a channel.
func (client *MessageTag) GetAll(channelId string, around string, before string, after string, limit int) ([]Message, error) {
    pathParams := make(map[string]interface{})
    pathParams["channel_id"] = channelId

    queryParams := make(map[string]interface{})
    queryParams["around"] = around
    queryParams["before"] = before
    queryParams["after"] = after
    queryParams["limit"] = limit

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/channels/:channel_id/messages", pathParams))
    if err != nil {
        return []Message{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return []Message{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return []Message{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return []Message{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data []Message
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return []Message{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return []Message{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return []Message{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    return []Message{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Get Retrieves a specific message in the channel. Returns a message object on success.
func (client *MessageTag) Get(channelId string, messageId string) (Message, error) {
    pathParams := make(map[string]interface{})
    pathParams["channel_id"] = channelId
    pathParams["message_id"] = messageId

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/channels/:channel_id/messages/:message_id", pathParams))
    if err != nil {
        return Message{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return Message{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return Message{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return Message{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Message{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Message{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Message{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    return Message{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Create Post a message to a guild text or DM channel. Returns a message object. Fires a Message Create Gateway event. See message formatting for more information on how to properly format messages.
func (client *MessageTag) Create(channelId string, payload Message) (Message, error) {
    pathParams := make(map[string]interface{})
    pathParams["channel_id"] = channelId

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/channels/:channel_id/messages", pathParams))
    if err != nil {
        return Message{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()

    raw, err := json.Marshal(payload)
    if err != nil {
        return Message{}, err
    }

    var reqBody = bytes.NewReader(raw)

    req, err := http.NewRequest("POST", u.String(), reqBody)
    if err != nil {
        return Message{}, err
    }

    req.Header.Set("Content-Type", "application/json")

    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return Message{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return Message{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Message{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Message{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Message{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    return Message{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Update Edit a previously sent message. The fields content, embeds, and flags can be edited by the original message author. Other users can only edit flags and only if they have the MANAGE_MESSAGES permission in the corresponding channel. When specifying flags, ensure to include all previously set flags/bits in addition to ones that you are modifying. Only flags documented in the table below may be modified by users (unsupported flag changes are currently ignored without error).
func (client *MessageTag) Update(channelId string, messageId string, payload Message) (Message, error) {
    pathParams := make(map[string]interface{})
    pathParams["channel_id"] = channelId
    pathParams["message_id"] = messageId

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/channels/:channel_id/messages/:message_id", pathParams))
    if err != nil {
        return Message{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()

    raw, err := json.Marshal(payload)
    if err != nil {
        return Message{}, err
    }

    var reqBody = bytes.NewReader(raw)

    req, err := http.NewRequest("PATCH", u.String(), reqBody)
    if err != nil {
        return Message{}, err
    }

    req.Header.Set("Content-Type", "application/json")

    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return Message{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return Message{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Message{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Message{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Message{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    return Message{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Remove Delete a message. If operating on a guild channel and trying to delete a message that was not sent by the current user, this endpoint requires the MANAGE_MESSAGES permission.
func (client *MessageTag) Remove(channelId string, messageId string) (error) {
    pathParams := make(map[string]interface{})
    pathParams["channel_id"] = channelId
    pathParams["message_id"] = messageId

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/channels/:channel_id/messages/:message_id", pathParams))
    if err != nil {
        return err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("DELETE", u.String(), nil)
    if err != nil {
        return err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        return nil
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    return errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Crosspost Crosspost a message in an Announcement Channel to following channels. This endpoint requires the SEND_MESSAGES permission, if the current user sent the message, or additionally the MANAGE_MESSAGES permission, for all other messages, to be present for the current user.
func (client *MessageTag) Crosspost(channelId string, messageId string) (Message, error) {
    pathParams := make(map[string]interface{})
    pathParams["channel_id"] = channelId
    pathParams["message_id"] = messageId

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/channels/:channel_id/messages/:message_id/crosspost", pathParams))
    if err != nil {
        return Message{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("POST", u.String(), nil)
    if err != nil {
        return Message{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return Message{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return Message{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Message{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Message{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Message{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    return Message{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// GetReactionsByEmoji 
func (client *MessageTag) GetReactionsByEmoji(channelId string, messageId string, emoji string, _type int, after string, limit int) ([]User, error) {
    pathParams := make(map[string]interface{})
    pathParams["channel_id"] = channelId
    pathParams["message_id"] = messageId
    pathParams["emoji"] = emoji

    queryParams := make(map[string]interface{})
    queryParams["type"] = _type
    queryParams["after"] = after
    queryParams["limit"] = limit

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/channels/:channel_id/messages/:message_id/reactions/:emoji", pathParams))
    if err != nil {
        return []User{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return []User{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return []User{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return []User{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data []User
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return []User{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return []User{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return []User{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    return []User{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// DeleteAllReactions 
func (client *MessageTag) DeleteAllReactions(channelId string, messageId string) (error) {
    pathParams := make(map[string]interface{})
    pathParams["channel_id"] = channelId
    pathParams["message_id"] = messageId

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/channels/:channel_id/messages/:message_id/reactions", pathParams))
    if err != nil {
        return err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("DELETE", u.String(), nil)
    if err != nil {
        return err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        return nil
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    return errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}




func NewMessageTag(httpClient *http.Client, parser *sdkgen.Parser) *MessageTag {
	return &MessageTag{
        internal: &sdkgen.TagAbstract{
            HttpClient: httpClient,
            Parser: parser,
        },
	}
}
