
// message_allowed_mentions automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk
type MessageAllowedMentions struct {
    Parse []string `json:"parse"`
    Roles []string `json:"roles"`
    Users []string `json:"users"`
    RepliedUser bool `json:"replied_user"`
}
