
// message_reference automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type MessageReference struct {
    MessageId string `json:"message_id"`
    ChannelId string `json:"channel_id"`
    GuildId string `json:"guild_id"`
    FailIfNotExists bool `json:"fail_if_not_exists"`
}
