
// message_embed automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type MessageEmbed struct {
    Title string `json:"title"`
    Type string `json:"type"`
    Description string `json:"description"`
    Url string `json:"url"`
    Timestamp string `json:"timestamp"`
    Color int `json:"color"`
}

